#   _____                    _____                        _
#  / ____|                  |  __ \                      | |
# | (___   ___ ___  _ __ ___| |__) |___  ___ ___  _ __ __| | ___ _ __
#  \___ \ / __/ _ \| '__/ _ \  _  // _ \/ __/ _ \| '__/ _` |/ _ \ '__|
#  ____) | (_| (_) | | |  __/ | \ \  __/ (_| (_) | | | (_| |  __/ |
# |_____/ \___\___/|_|  \___|_|  \_\___|\___\___/|_|  \__,_|\___|_|   by yh

# 設定

# ブロック破壊時やモブ討伐時のスコア獲得メッセージ
show-score-messages: false

# スコアからウォレットへの交換レート (例: 100スコア = 1ウォレット)
score-to-wallet-rate: 100
